//
// ArtworksEndpointsAPI.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
import UIKit
#endif

open class ArtworksEndpointsAPI {

    /**
     Artworks Endpoint
     
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @discardableResult
    open class func getArtworks(page: Int, apiResponseQueue: DispatchQueue = OpenAPIClientAPI.apiResponseQueue, completion: @escaping ((_ data: ResponseModel?, _ error: Error?) -> Void)) -> RequestTask {
        return getArtworksWithRequestBuilder(page: page).execute(apiResponseQueue) { result in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

///    Get Image
///
///    - parameter apiResponseQueue: The queue on which api response is dispatched.
///    - parameter completion: completion handler to receive the data and the error objects
///    */
   @discardableResult
    open class func getImage(imageId: String, iiifUrl: String, apiResponseQueue: DispatchQueue = OpenAPIClientAPI.apiResponseQueue, completion: @escaping ((_ data: Data?, _ error: Error?) -> Void)) -> RequestTask {
       return getImageRequestBuilder(imageId: imageId, iiifUrl: iiifUrl).execute(apiResponseQueue) { result in
           switch result {
           case let .success(response):
               completion(response.body, nil)
           case let .failure(error):
               completion(nil, error)
           }
       }
   }


    /**
     Artworks Endpoint
     - GET /artworks
     - A list of all artworks sorted by last updated date in descending order.
     - returns: RequestBuilder<ResponseModel> 
     */
    open class func getArtworksWithRequestBuilder(page: Int) -> RequestBuilder<ResponseModel> {
        let localVariablePath = "/artworks"
        let localVariableURLString = OpenAPIClientAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = ["page": page]

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<ResponseModel>.Type = OpenAPIClientAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters)
    }

    open class func getImageRequestBuilder(imageId: String, iiifUrl: String) -> RequestBuilder<Data> {
        let size = "/full/200,/0/default.jpg"

        let localVariableURLString = iiifUrl + "/" + imageId + size

        let localVariableParameters: [String: Any]? = [:]

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<Data>.Type = OpenAPIClientAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters)
    }

}
