//
// ArtworkDataContexts.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct ArtworkDataContexts: Codable, Hashable {

    public var groupings: [AnyCodable]

    public init(groupings: [AnyCodable]) {
        self.groupings = groupings
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case groupings
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(groupings, forKey: .groupings)
    }
}
