//
// Config.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct Config: Codable, Hashable {

    public var iiifUrl: String
    public var websiteUrl: String

    public init(iiifUrl: String, websiteUrl: String) {
        self.iiifUrl = iiifUrl
        self.websiteUrl = websiteUrl
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case iiifUrl = "iiif_url"
        case websiteUrl = "website_url"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(iiifUrl, forKey: .iiifUrl)
        try container.encode(websiteUrl, forKey: .websiteUrl)
    }
}

