//
// Info.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct Info: Codable, Hashable {

    public var licenseText: String
    public var licenseLinks: [AnyCodable]
    public var version: String

    public init(licenseText: String, licenseLinks: [AnyCodable], version: String) {
        self.licenseText = licenseText
        self.licenseLinks = licenseLinks
        self.version = version
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case licenseText = "license_text"
        case licenseLinks = "license_links"
        case version
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(licenseText, forKey: .licenseText)
        try container.encode(licenseLinks, forKey: .licenseLinks)
        try container.encode(version, forKey: .version)
    }
}
