//
// Pagination.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct Pagination: Codable, Hashable {

    public var total: Double?
    public var limit: Double?
    public var offset: Double?
    public var totalPages: Double
    public var currentPage: Double
    public var nextUrl: String

    public init(total: Double?, limit: Double?, offset: Double?, totalPages: Double, currentPage: Double, nextUrl: String) {
        self.total = total
        self.limit = limit
        self.offset = offset
        self.totalPages = totalPages
        self.currentPage = currentPage
        self.nextUrl = nextUrl
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case total
        case limit
        case offset
        case totalPages = "total_pages"
        case currentPage = "current_page"
        case nextUrl = "next_url"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(total, forKey: .total)
        try container.encode(limit, forKey: .limit)
        try container.encode(offset, forKey: .offset)
        try container.encode(totalPages, forKey: .totalPages)
        try container.encode(currentPage, forKey: .currentPage)
        try container.encode(nextUrl, forKey: .nextUrl)
    }
}

