//
// ResponseArtworks.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct ResponseArtworks: Codable, Hashable {

    public var pagination: Pagination?
    public var data: [ArtworkData]?
    public var info: Info?
    public var config: Config?

    public init(pagination: Pagination? = nil, data: [ArtworkData]? = nil, info: Info? = nil, config: Config? = nil) {
        self.pagination = pagination
        self.data = data
        self.info = info
        self.config = config
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case pagination
        case data
        case info
        case config
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(pagination, forKey: .pagination)
        try container.encodeIfPresent(data, forKey: .data)
        try container.encodeIfPresent(info, forKey: .info)
        try container.encodeIfPresent(config, forKey: .config)
    }
}
