//
// Thumbnail.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct Thumbnail: Codable, Hashable {

    public var lqip: String
    public var width: Double
    public var height: Double
    public var altText: String

    public init(lqip: String, width: Double, height: Double, altText: String) {
        self.lqip = lqip
        self.width = width
        self.height = height
        self.altText = altText
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case lqip
        case width
        case height
        case altText = "alt_text"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(lqip, forKey: .lqip)
        try container.encode(width, forKey: .width)
        try container.encode(height, forKey: .height)
        try container.encode(altText, forKey: .altText)
    }
}

